-- Выход из режима "ВСТАВКА" (insert)
vim.keymap.set('i', '<C-i>', '<escape>', {noremap = true})

-- Быстрый сдвиг текста в режиме 'ВСТАВКА' (insert)
-- (надо будет проработать в визуальном режиме на множество строк)
vim.keymap.set({'i', 'v'}, '<tab>', '<cmd>><cr>', {noremap = true})
vim.keymap.set({'i', 'v'}, '<s-tab>', '<cmd><<cr>', {noremap = true})

-- Отключение стрелок
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<left>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<up>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<right>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<down>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<s-left>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<s-up>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<s-right>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<s-down>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<c-left>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<c-up>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<c-right>', '', {noremap = true})
vim.keymap.set({'n', 'i', 'x', 'o', 'v'}, '<c-down>', '', {noremap = true})
